[package]
name = "deltac"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
either = "1.15.0"
enum_dispatch = "0.3.13"
inkwell = { version = "0.5.0", features = ["llvm18-0"] }
llvm-sys = "180"
subenum = "1.1.2"
tempfile = "3.20.0"
